version: 2

# Specify the build environment
sphinx:
  configuration: docs/conf.py

# Define the Python version and install dependencies
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: docs/requirements.txt

formats:
  - pdf
  - epub
