name: Build

# on: [push, pull_request]
on:
  push:
    tags:
      - 'v*'

env:
  CIBW_SKIP: pp*

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [ubuntu-22.04, windows-2019, macos-12, macos-14]
        os: [windows-2019, macos-14]

    steps:
      - uses: actions/checkout@v4

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.18.0

      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: cibw-wheels-${{ matrix.os }}-${{ strategy.job-index }}
      #     path: ./wheelhouse/*.whl

      - name: Release wheels
        uses: softprops/action-gh-release@v1
        with:
          files: ./wheelhouse*.whl